version: '3'
services:
  opensearch-node:
    build: .
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0-SNAPSHOT
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge